flags distunguish bet cleanup and debugging

diff --git a/run_pipeline b/run_pipeline
--- a/run_pipeline
+++ b/run_pipeline
@@ -7,6 +7,7 @@ SGE_TASK_ID=0					# index of region (default: all (0))
 myregion=""					# user specified region (default NULL)
 mypartition=""					# user specified partition (default NULL)
 debug=0						# bool to turn on debugging (default: no)
+cleanup=1					# bool to turn on cleanup (default: yes)
 filter=1					# bool to do SAVI filter (default: yes)
 mapq=10						# pileup flag: skip alignments with mapQ less than (default: 10)
 stepstr=1245					# what steps to run (default: 1,2,4,5 - don't generate prior)
@@ -55,7 +56,8 @@ Options:
   --memory	the memory for the Java virtual machine in gigabytes (default: 6)
   --mindepth	the minimum read depth required in at least one sample - positions without this wont appear in pileup file (default: 5)
   --mapqual	pileup flag: skip alignments with mapQ less than this (default: 10)
-  --debug	do not delete tmp intermediate files  (default: off)
+  --noclean	do not delete tmp intermediate files  (default: off)
+  --debug	echo commands  (default: off)
   --nofilter	do not use SAVI comparison filter (default: off) (you should use this option if NOT doing comparisons)
   --scripts	location of scripts dir  (directory where this script resides - use this option only if qsub-ing)
   --ann-genome  name of the SnpEff genome with which to annotate (default: GRCh37.71)
@@ -155,6 +157,9 @@ while [ $# -gt 0 ]; do
 	elif [  "$1" == "-noncoding" -o "$1" == "--noncoding" ]; then
 		shift; 
 		noncoding=1; 
+	elif [  "$1" == "-noclean" -o "$1" == "--noclean" ]; then
+		shift; 
+		cleanup=0; 
 	elif [  "$1" == "-debug" -o "$1" == "--debug" ]; then
 		shift; 
 		debug=1; 
@@ -196,13 +201,13 @@ done
 time1=$( date "+%s" )
 inputprior=${software}/savi/prior_unif01	# input prior (default: savi/prior_unif01)
 
-echo "[start]"
+echo "[START] "`date`
 echo "[pwd] "`pwd`
-echo "[date] "`date`
 echo "[output directory] "$outputdir
 echo "[java memory] "$java_memory
 echo "[index] "$SGE_TASK_ID
 echo "[partition] "$mypartition
+echo "[cleanup bool] "$cleanup
 echo "[debug bool] "$debug
 echo "[filter] "$filter
 echo "[mapq qual threshold for samtools mpileup] "$mapq
@@ -264,8 +269,10 @@ fi
 
 mkdir -p ${outputdir}
 
-# turn on debugging
-# set -eux
+# turn on debugging 
+if [ $debug -eq 1 ]; then
+	set -eux
+fi
 
 # if region set 
 if [ ! -z "${myregion}" ]; then
@@ -434,8 +441,8 @@ if [[ $stepstr == *5* ]]; then
 		# annotate all present variants
 		java -Xmx${java_memory}G -jar $( which SnpSift.jar ) annotate ${i} -noLog ${outputdir2}/tmp_${SGE_TASK_ID}.eff_$(($myindex - 1)).all.vcf > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.all.vcf
 
-		# if not debug, delete tmp files
-		if [ $debug -eq 0 ]; then
+		# if cleanup, delete tmp files
+		if [ $cleanup -eq 1 ]; then
 			rm ${outputdir2}/tmp_${SGE_TASK_ID}.eff_$(($myindex - 1)).all.vcf
 		fi
 
@@ -506,8 +513,8 @@ if [[ $stepstr == *6* ]]; then
 fi
 
 echo "[STEP CLEANUP] clean up"
-# if not debug
-if [ $debug -eq 0 ]; then 
+# if cleanup
+if [ $cleanup -eq 1 ]; then 
 	rm -f ${outputdir}/tmp_mpile.${SGE_TASK_ID}.txt 
 	rm -f ${outputdir}/${SGE_TASK_ID}.all.vcf.bgz*
 	rm -f ${outputdir}/${SGE_TASK_ID}.vcf.bgz*
@@ -520,5 +527,5 @@ fi
 rm -f ${outputdir}/savi/out/finalsavi.vcf
 
 time2=$( date "+%s" )
-echo [deltat] $(( $time2 - $time1 ))
-echo [End] `date`
+echo "[deltat] "$(( $time2 - $time1 ))
+echo "[END] "`date`
