major revisions (under jiguang's guidance)

diff --git a/run_pipeline b/run_pipeline
--- a/run_pipeline
+++ b/run_pipeline
@@ -9,15 +9,16 @@ mypartition=""					# user specified partition (default NULL)
 debug=0						# bool to turn on debugging (default: no)
 filter=1					# bool to do SAVI filter (default: yes)
 mapq=10						# pileup flag: skip alignments with mapQ less than (default: 10)
-stepstr=12345					# what steps to run (default: 1 thro 5)
+stepstr=1245					# what steps to run (default: 1,2,4,5)
 software=$( dirname $( readlink -m $0 ) )	# directory where to look for scripts
 input_bams=""					# input bam files
 sample_names=""					# sample names in a comma-delimited list
 num_bams=2					# number of input bams (default: 2)
 compsamp="2:1"					# the indices of sample to compare with savi (default: 2:1 - i.e., tumor vs norm)
 cutoff=5 					# min read depth cutoff
-anngenome="hg19"				# annotating reference for SnpEff (default: hg19)
-# anngenome="GRCh37.71"				# annotating reference for SnpEff (default: hg19)
+anngenome="GRCh37.71"				# annotating reference for SnpEff (if hg19, chrM; if GRCh37.71, chrMT)
+# anngenome="hg19"
+noncoding=0   					# use snpEff to find only all transcripts, not just protein transcripts (default: off)
 annvcf=""					# annotating vcfs in comma-delimited list (default: none)
 						# common hg19 annotating vcfs in comma-delimited list
 savi_precision=0				# the SAVI precision, from the Hossein fix
@@ -58,8 +59,9 @@ Options:
   --nofilter	do not use SAVI comparison filter (default: off) (you should use this option if NOT doing comparisons)
   --scripts	location of scripts dir  (directory where this script resides - use this option only if qsub-ing)
   --ann-genome  name of the SnpEff genome with which to annotate (default: hg19)
+  --noncoding	use snpEff to find all transcripts, not just only protein transcripts (default: off)
   --ann-vcf     comma-delimited list of vcfs with which to provide additional annotation (default: none)
-  --prior	input prior (default: savi/unif_prior01)
+  --prior	input prior (default: savi/prior_unif01)
   --precision	the SAVI precision
   --help	print this message and exit
 
@@ -150,6 +152,9 @@ while [ $# -gt 0 ]; do
 		shift; 
 		annvcf=$1;
 		shift
+	elif [  "$1" == "-noncoding" -o "$1" == "--noncoding" ]; then
+		shift; 
+		noncoding=1; 
 	elif [  "$1" == "-debug" -o "$1" == "--debug" ]; then
 		shift; 
 		debug=1; 
@@ -189,18 +194,31 @@ while [ $# -gt 0 ]; do
 done
 
 time1=$( date "+%s" )
-inputprior=${software}/savi/unif_prior01	# input prior (default: savi/unif_prior01)
+inputprior=${software}/savi/prior_unif01	# input prior (default: savi/prior_unif01)
 
 echo "[start]"
 echo "[pwd] "`pwd`
 echo "[date] "`date`
+echo "[output directory] "$outputdir
+echo "[java memory] "$java_memory
 echo "[index] "$SGE_TASK_ID
-echo "[output_dir] "$outputdir
-echo "[steps] "$stepstr
-echo "[debug] "$debug
-echo "[bam files] "$input_bams
+echo "[partition] "$mypartition
+echo "[debug bool] "$debug
+echo "[filter] "$filter
+echo "[mapq qual threshold for samtools mpileup] "$mapq
+echo "[savi steps to run] "$stepstr
+echo "[software directory] "$software
+echo "[input bams] "$input_bams
 echo "[sample names] "$sample_names
-echo "[scripts dir] "$software
+echo "[number of bams] "$num_bams
+echo "[compsamp flag] "$compsamp
+echo "[read depth cutoff] "$cutoff
+echo "[annotating genome for snpEff] "$anngenome
+echo "[annotate noncoding bool] "$noncoding
+echo "[annotating list of vcfs] "$annvcf
+echo "[savi precision] "$savi_precision
+echo "[dependencies] "$required_programs
+echo "[savi proper dependencies] "$required_savi_programs
 
 # check for required programs
 for i in $required_programs; do 
@@ -247,7 +265,7 @@ fi
 mkdir -p ${outputdir}
 
 # turn on debugging
-set -eux
+# set -eux
 
 # if region set 
 if [ ! -z "${myregion}" ]; then
@@ -277,12 +295,12 @@ fi
 ### need to remove duplicate reads w Picard
 # or else get false positives
 
+echo -e "\nStarting Pipeline ...\n"
+
 if [[ $stepstr == *1* ]]; then
 	echo "[STEP1] pileup"
 	### mpileup
 	# for mpileup - note the -d flag: "max per-BAM depth to avoid excessive memory usage [250]." The default of 250 is way too low, so we jack it up
-	# -B - disable BAQ computation
-	# -q 10 - skip alignments with mapQ smaller than INT
 	# awk line - we want only lines where normal has depth > cutoff, and at least one of the tumor samples has depth > cutoff
 	samtools mpileup -B -q ${mapq} -d 100000 -L 100000 ${regionflag} -f $ref ${input_bams} \
 	    | awk -v num=${num_bams} -v cutoff=${cutoff} '{true=0; for (i = 1; i <= num-1; i++) {if ($(4+i*3) > cutoff) {true=1}}; if (num==1 && $4>cutoff) {print} else if (num>1 && $4>cutoff && true) {print}}' \
@@ -301,8 +319,10 @@ if [[ $stepstr == *2* ]]; then
 	echo "[STEP2] pileup2vcf"
 	### Oscan
 	# call everything, variants and non-variants alike
+	# use awk to patch a problem that samtools mpileup does not include indels in the total read count - with the exception of *s
 	cat ${outputdir}/tmp_mpile.${SGE_TASK_ID}.txt | ${software}/savi/pileup2multiallele_vcf --all --header \
-             | tee ${outputdir}/${SGE_TASK_ID}.all.vcf | awk '{ if ($0 ~ /^#/ || toupper($4) != toupper($5)) {print}}' | bgzip > ${outputdir}/${SGE_TASK_ID}.vcf.bgz
+	    | awk '{if ( $0 ~ /^#/) {print} else if (length($4) == 1 && length($5) == 1) {print} else { for (i = 1; i <= NF; i++) { if (i==1) {printf $i} else if (i < 10) {printf "\t"$i} else {split($i,x,":"); printf "\t"; for (j = 1; j <= length(x); j++) {if (j==1) {printf x[j]} else if (j==3) {printf ":"x[3]+x[6]} else {printf ":"x[j]}} }}; printf "\n"}}' \
+	    | tee ${outputdir}/${SGE_TASK_ID}.all.vcf | awk '{ if ($0 ~ /^#/ || toupper($4) != toupper($5)) {print}}' | bgzip > ${outputdir}/${SGE_TASK_ID}.vcf.bgz
 
 	cat ${outputdir}/${SGE_TASK_ID}.all.vcf | bgzip > ${outputdir}/${SGE_TASK_ID}.all.vcf.bgz
 	rm ${outputdir}/${SGE_TASK_ID}.all.vcf
@@ -326,13 +346,13 @@ if [[ $stepstr == *3* ]]; then
 	#for i in $( seq 1 $num_bams ); do
 	# for samples in the compsamp string
 	for i in $( echo ${compsamp} | sed 's|,|\n|g; s|:|\n|g' | sort -u ); do
-		mkdir -p ${outputdir}/savi_${SGE_TASK_ID}/prior${i}
+		mkdir -p ${outputdir}/savi/prior${i}
 		${software}/make_prior.py --verbose \
 		      --name s${i} \
 		      --iteration 10 \
 		      --prior ${inputprior} \
 		      --sampleindex ${i} \
-		      --outputdir ${outputdir}/savi_${SGE_TASK_ID}/prior${i} \
+		      --outputdir ${outputdir}/savi/prior${i} \
 		      --input ${outputdir}/${SGE_TASK_ID}.all.vcf.bgz;
 	done;
 
@@ -342,92 +362,109 @@ fi
 if [[ $stepstr == *4* ]]; then
 	echo "[STEP4] run_savi"
 	### run_savi.py
-	mkdir -p ${outputdir}/savi_${SGE_TASK_ID}/out
+	mkdir -p ${outputdir}/savi/out
 
 	# prior string for priors specified in compsamp
-	# if compsamp="2:1", it should look like this - 1:${outputdir}/savi_${SGE_TASK_ID}/prior1/prior,2:${outputdir}/savi_${SGE_TASK_ID}/prior2/prior
-	priorstring=$( for i in $( echo ${compsamp} | sed 's|,|\n|g; s|:|\n|g' | sort -u ); do echo -n "${i}:${outputdir}/savi_${SGE_TASK_ID}/prior${i}/prior,"; done | sed 's|,$||'; echo )
+	# if compsamp="2:1", it should look like this - 1:${outputdir}/savi/prior1/prior,2:${outputdir}/savi/prior2/prior
+	priorstring=$( for i in $( echo ${compsamp} | sed 's|,|\n|g; s|:|\n|g' | sort -u ); do echo -n "${i}:${software}/savi/prior_diploid01,"; done | sed 's|,$||'; echo )
 
 	# invert filter variable
 	keepfreqfile=$( echo $filter | awk '{x=$1; print !x}' )
 
-	${software}/run_savi.py --verbose \
+	${software}/run_savi.py \
 	     --input ${outputdir}/${SGE_TASK_ID}.vcf.bgz \
 	     --name savi_${SGE_TASK_ID} \
 	     --sample ${compsamp} \
 	     --prior ${priorstring} \
 	     --saviprecision ${savi_precision} \
 	     --keepfreqfile ${keepfreqfile} \
-	     --outputdir ${outputdir}/savi_${SGE_TASK_ID}/out
+	     --outputdir ${outputdir}/savi/out
 
 	# run_savi.py output files:
 	# freqsavi.vcf.bgz - adds presence frequencies to all present variants 
 	# finalsavi.vcf.bgz - add frequency deltas for sample comparisons to all present variants 
 	# finalfilter.vcf - filter all present mutations for somatic variants
 
+	# if savi comparisons
 	if [ $filter -eq 1 ]; then 
-		# make a string for the vcffilter - e.g., if $compsamp is 2:1,3:1,5 then $filterstring will be PD21_L > 0 | PD31_L > 0
-		filterstring=$( echo $compsamp | perl -ne '{chomp($line = $_); @myarr = split(/,/, $line); foreach my $elt (@myarr) {if ($elt =~ s/://) {print "PD".$elt."_L > 0 | "}}}' | sed 's|\| $||' )
-		# get somatic variants
-		vcffilter -f "${filterstring}" ${outputdir}/savi_${SGE_TASK_ID}/out/finalsavi.vcf.bgz > ${outputdir}/savi_${SGE_TASK_ID}/out/finalfilter.vcf 
 		# unzip all present variants
-		zcat ${outputdir}/savi_${SGE_TASK_ID}/out/finalsavi.vcf.bgz > ${outputdir}/savi_${SGE_TASK_ID}/out/finalsavi.vcf
+		zcat ${outputdir}/savi/out/finalsavi.vcf.bgz > ${outputdir}/savi/out/finalsavi.vcf
+	# if no savi comparisons (e.g., unpaired sample)
 	else
-		# if unpaired sample
-		zcat ${outputdir}/savi_${SGE_TASK_ID}/out/freqsavi.vcf.bgz > ${outputdir}/savi_${SGE_TASK_ID}/out/finalfilter.vcf     
-		rm ${outputdir}/savi_${SGE_TASK_ID}/out/freqsavi.vcf.bgz ${outputdir}/savi_${SGE_TASK_ID}/out/freqsavi.vcf.bgz.tbi
+		zcat ${outputdir}/savi/out/freqsavi.vcf.bgz > ${outputdir}/savi/out/finalsavi.vcf  
+		rm ${outputdir}/savi/out/freqsavi.vcf.bgz ${outputdir}/savi/out/freqsavi.vcf.bgz.tbi
 	fi
 
 	# if SAVI vcf empty
-	if [ $( cat ${outputdir}/savi_${SGE_TASK_ID}/out/finalfilter.vcf | sed '/^#/d' | head | wc -l ) == 0 ]; then
-		echo "[WARNING] SAVI vcf file is empty"
-		# exit 0;
+	if [ $( cat ${outputdir}/savi/out/finalsavi.vcf | sed '/^#/d' | head | wc -l ) == 0 ]; then
+		echo "[HALT SCRIPT] SAVI vcf file is empty"
+		exit 0;
 	fi
 
 	echo "[date 4] "`date`;
 fi
 
 ### SnpEff
-outputdir2=${outputdir}/ann_${SGE_TASK_ID}
+outputdir2=${outputdir}/ann
 if [[ $stepstr == *5* ]]; then
 	echo "[STEP5] annotation"
 	mkdir -p ${outputdir2}
 
 	# annotate all present variants, somatic variants
-	mysuffix="all.vcf"
-	for myfile in ${outputdir}/savi_${SGE_TASK_ID}/out/finalsavi.vcf ${outputdir}/savi_${SGE_TASK_ID}/out/finalfilter.vcf; do 
-		if [ -e ${myfile} ]; then
-			java -Xmx${java_memory}G -jar $( which snpEff.jar ) -c $( which snpEff.config ) $anngenome -noStats -v -lof  -canon -no-downstream -no-intergenic -no-intron -no-upstream -no-utr ${myfile} > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_0.${mysuffix}
-		fi	
-		mysuffix="vcf"
-	done
+	if [ $noncoding -eq 0 ]; then
+		if [ -e ${outputdir}/savi/out/finalsavi.vcf ]; then
+			java -Xmx${java_memory}G -jar $( which snpEff.jar ) ann ${anngenome} -noLog -q -c $( which snpEff.config ) -formatEff -noStats -lof -onlyProtein -canon -no-downstream -no-intergenic -no-upstream -no-utr ${outputdir}/savi/out/finalsavi.vcf > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_0.all.vcf
+		else
+			java -Xmx${java_memory}G -jar $( which snpEff.jar ) ann ${anngenome} -noLog -q -c $( which snpEff.config ) -formatEff -noStats -lof -onlyProtein -canon -no-downstream -no-intergenic -no-upstream -no-utr ${outputdir}/savi/out/finalsavi.vcf.bgz > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_0.all.vcf
+		fi
+	else
+		if [ -e ${outputdir}/savi/out/finalsavi.vcf ]; then
+			java -Xmx${java_memory}G -jar $( which snpEff.jar ) ann ${anngenome} -noLog -q -c $( which snpEff.config ) -formatEff -noStats -lof -canon ${outputdir}/savi/out/finalsavi.vcf > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_0.all.vcf
+		else
+			java -Xmx${java_memory}G -jar $( which snpEff.jar ) ann ${anngenome} -noLog -q -c $( which snpEff.config ) -formatEff -noStats -lof -canon ${outputdir}/savi/out/finalsavi.vcf.bgz > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_0.all.vcf
+		fi
+	fi
 
 	# loop through all annotating vcfs
 	myindex=1 						# define index variable for the loop
 	num_vcfs=$( echo ${annvcf} | sed 's|,| |g' | wc -w )	# get the total number of annotating vcfs
 	for i in $( echo ${annvcf} | sed 's|,| |g' ); do 
-		# annotate all present variants, somatic variants
-		for mysuffix in all.vcf vcf; do
-			if [ -e ${outputdir2}/tmp_${SGE_TASK_ID}.eff_$(($myindex - 1)).${mysuffix} ]; then
-				java -Xmx${java_memory}G -jar $( which SnpSift.jar ) annotate ${i} -v ${outputdir2}/tmp_${SGE_TASK_ID}.eff_$(($myindex - 1)).${mysuffix} > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.${mysuffix}
+		# annotate all present variants
+		java -Xmx${java_memory}G -jar $( which SnpSift.jar ) annotate ${i} -noLog ${outputdir2}/tmp_${SGE_TASK_ID}.eff_$(($myindex - 1)).all.vcf > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.all.vcf
 
-				# if not debug, delete tmp files
-				if [ $debug -eq 0 ]; then
-					rm ${outputdir2}/tmp_${SGE_TASK_ID}.eff_$(($myindex - 1)).${mysuffix}
-				fi
+		# if not debug, delete tmp files
+		if [ $debug -eq 0 ]; then
+			rm ${outputdir2}/tmp_${SGE_TASK_ID}.eff_$(($myindex - 1)).all.vcf
+		fi
 
-				# if final iteration of loop, convert from vcf to human readable tab-delimited report
-				if [ $myindex -eq $num_vcfs ]; then
-					# if sample names given, use them
-					if [ -z $sample_names ]; then 
-						cat ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.${mysuffix} | ${software}/util/vcf2report.py > ${outputdir2}/report.${mysuffix}.txt
-					else
-						cat ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.${mysuffix} | ${software}/util/vcf2report.py --samples $sample_names > ${outputdir2}/report.${mysuffix}.txt
-					fi
-				fi
+		# if final iteration of loop, convert from vcf to human readable tab-delimited report
+		if [ $myindex -eq $num_vcfs ]; then
+			# if savi comparisons
+			if [ $filter -eq 1 ]; then 
+				# make a string for the vcffilter - e.g., if $compsamp is 2:1,3:1,5 then $filterstring will be PD21_L > 0 | PD31_L > 0
+				filterstring=$( echo $compsamp | perl -ne '{chomp($line = $_); @myarr = split(/,/, $line); foreach my $elt (@myarr) {if ($elt =~ s/://) {print "PD".$elt."_L > 0 | "}}}' | sed 's|\| $||' )
+				# reverse filter
+				filterstring_reverse=$( echo $compsamp | perl -ne '{chomp($line = $_); @myarr = split(/,/, $line); foreach my $elt (@myarr) {if ($elt =~ s/://) {print "PD".$elt."_U < 0 | "}}}' | sed 's|\| $||' )
+				echo "[filterstring] $filterstring"
+				echo "[reverse filterstring] $filterstring_reverse"
+				# get somatic variants
+				vcffilter -f "${filterstring}" ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.all.vcf > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.filter.vcf
+				vcffilter -f "${filterstring_reverse}" ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.all.vcf > ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.revfilter.vcf
 			fi
-		done
+
+			reportoptions=""
+			# if sample names given, use them
+			if [ -z $sample_names ]; then 
+				reportoptions="--samples $sample_names"
+			fi
+
+			cat ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.all.vcf | ${software}/util/vcf2report_for_v4.1.C.py ${reportoptions} > ${outputdir2}/report.all.txt
+			cat ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.filter.vcf | ${software}/util/vcf2report_for_v4.1.C.py ${reportoptions} > ${outputdir2}/report.filter.txt
+			cat ${outputdir2}/tmp_${SGE_TASK_ID}.eff_${myindex}.revfilter.vcf | ${software}/util/vcf2report_for_v4.1.C.py ${reportoptions} > ${outputdir2}/report.revfilter.txt
+		fi
+
 		myindex=$(($myindex + 1))
+
 	done
 
 	echo "[date 5] "`date`;
@@ -448,7 +485,7 @@ if [[ $stepstr == *6* ]]; then
 	    ${outputdir3}/${SGE_TASK_ID}.tumor
 
 	cat ${outputdir3}/${SGE_TASK_ID}.tumor.copynumber | sed '1d' | awk 'BEGIN{OFS="\t"}{print "1","40",int($6+0.5),int($5+$6+0.5)}' > ${outputdir3}/${SGE_TASK_ID}.qvt.txt
-	${software}/make_prior.py -n ${SGE_TASK_ID}.tumor -j 10 -p ${software}/savi/unif_prior01 -o ${outputdir3}/prior --qvt ${outputdir3}/${SGE_TASK_ID}.qvt.txt
+	${software}/make_prior.py -n ${SGE_TASK_ID}.tumor -j 10 -p ${software}/savi/prior_unif01 -o ${outputdir3}/prior --qvt ${outputdir3}/${SGE_TASK_ID}.qvt.txt
 
 	mymean=$( cat ${outputdir3}/${SGE_TASK_ID}.qvt.txt | awk 'BEGIN{x=0}{x=x+$3/$4;}END{print x/NR}' )
 
@@ -459,7 +496,7 @@ if [[ $stepstr == *6* ]]; then
 
 	# Loss of Heterozygosity
 	zcat $outputdir/${SGE_TASK_ID}.vcf.bgz | ${software}/savi/make_qvt -1 -2s 2,1 \
-	   | ${software}/savi/savi_poster -pd ${outputdir}/savi_${SGE_TASK_ID}/prior2/prior ${outputdir}/savi_${SGE_TASK_ID}/prior1/prior \
+	   | ${software}/savi/savi_poster -pd ${outputdir}/savi/prior2/prior ${outputdir}/savi/prior1/prior \
 	   | ${software}/savi/savi_comp 2 0 \
 	   | awk 'BEGIN{print "loh_call\tloh_call_posterior"}{print}' > ${outputdir3}/${SGE_TASK_ID}.loh.txt
 
@@ -472,13 +509,13 @@ if [ $debug -eq 0 ]; then
 	rm -f ${outputdir}/tmp_mpile.${SGE_TASK_ID}.txt 
 	rm -f ${outputdir}/${SGE_TASK_ID}.all.vcf.bgz*
 	rm -f ${outputdir}/${SGE_TASK_ID}.vcf.bgz*
-	rm -f ${outputdir}/savi_${SGE_TASK_ID}/out/freqsavi.vcf.bgz*
+	rm -f ${outputdir}/savi/out/freqsavi.vcf.bgz*
 	rm -f ${outputdir3}/${SGE_TASK_ID}.qvt.txt
 	rm -f ${outputdir3}/${SGE_TASK_ID}.cnv.tmp.txt
 	rm -f ${outputdir3}/${SGE_TASK_ID}.tumor.copynumber
 fi
 # remove this because we already have the zipped version
-rm -f ${outputdir}/savi_${SGE_TASK_ID}/out/finalsavi.vcf
+rm -f ${outputdir}/savi/out/finalsavi.vcf
 
 time2=$( date "+%s" )
 echo [deltat] $(( $time2 - $time1 ))
